#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # Write your code here
    l=scores[0]
    h=scores[0]
    minC=0
    maxC=0
    for i in range(1,len(scores)):
        if scores[i]<l:
            minC +=1
            l=scores[i]
        if scores[i]>h:
            maxC +=1
            h=scores[i]
    return [maxC, minC]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
